# Generated by Django 3.2.5 on 2023-06-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=255)),
                ('field2', models.CharField(max_length=255)),
                ('field3', models.CharField(max_length=255)),
                ('field4', models.CharField(max_length=255)),
            ],
        ),
    ]
